In [11]:
import pandas as pd

In [12]:
data=pd.read_csv('wdbc_data.csv',header=None)

In [15]:
data.head()

0  1      2      3       4       5        6        7       8   \
0    842302  M  17.99  10.38  122.80  1001.0  0.11840  0.27760  0.3001   
1    842517  M  20.57  17.77  132.90  1326.0  0.08474  0.07864  0.0869   
2  84300903  M  19.69  21.25  130.00  1203.0  0.10960  0.15990  0.1974   
3  84348301  M  11.42  20.38   77.58   386.1  0.14250  0.28390  0.2414   
4  84358402  M  20.29  14.34  135.10  1297.0  0.10030  0.13280  0.1980   

        9    ...        22     23      24      25      26      27      28  \
0  0.14710   ...     25.38  17.33  184.60  2019.0  0.1622  0.6656  0.7119   
1  0.07017   ...     24.99  23.41  158.80  1956.0  0.1238  0.1866  0.2416   
2  0.12790   ...     23.57  25.53  152.50  1709.0  0.1444  0.4245  0.4504   
3  0.10520   ...     14.91  26.50   98.87   567.7  0.2098  0.8663  0.6869   
4  0.10430   ...     22.54  16.67  152.20  1575.0  0.1374  0.2050  0.4000   

       29      30       31  
0  0.2654  0.4601  0.11890  
1  0.1860  0.2750  0.08902  
2  0.2430  0.3613  0.08758  
3  0.2575  0.6638  0.17300  
4  0.1625  0.2364  0.07678  

[5 rows x 32 columns]

# Normalization of data

In [14]:
X = data.drop(1, axis=1)
y = data[1]
X=X.drop(0,axis=1)
X = (X - X.min()) / (X.max() - X.min())
X.head()

2         3         4         5         6         7         8   \
0  0.521037  0.022658  0.545989  0.363733  0.593753  0.792037  0.703140   
1  0.643144  0.272574  0.615783  0.501591  0.289880  0.181768  0.203608   
2  0.601496  0.390260  0.595743  0.449417  0.514309  0.431017  0.462512   
3  0.210090  0.360839  0.233501  0.102906  0.811321  0.811361  0.565604   
4  0.629893  0.156578  0.630986  0.489290  0.430351  0.347893  0.463918   

         9         10        11    ...           22        23        24  \
0  0.731113  0.686364  0.605518    ...     0.620776  0.141525  0.668310   
1  0.348757  0.379798  0.141323    ...     0.606901  0.303571  0.539818   
2  0.635686  0.509596  0.211247    ...     0.556386  0.360075  0.508442   
3  0.522863  0.776263  1.000000    ...     0.248310  0.385928  0.241347   
4  0.518390  0.378283  0.186816    ...     0.519744  0.123934  0.506948   

         25        26        27        28        29        30        31  
0  0.450698  0.601136  0.619292  0.568610  0.912027  0.598462  0.418864  
1  0.435214  0.347553  0.154563  0.192971  0.639175  0.233590  0.222878  
2  0.374508  0.483590  0.385375  0.359744  0.835052  0.403706  0.213433  
3  0.094008  0.915472  0.814012  0.548642  0.884880  1.000000  0.773711  
4  0.341575  0.437364  0.172415  0.319489  0.558419  0.157500  0.142595  

[5 rows x 30 columns]

# 60-40 Split repeated 10 times for both Kernels

In [16]:
import numpy as np
def svm_poly(a):
    conf_mat=[]
    for i in range(10):
        from sklearn.model_selection import train_test_split
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size =0.40)
        from sklearn.svm import SVC
        svclassifier = SVC(kernel='poly',degree=a)
        svclassifier.fit(X_train, y_train)
        y_pred = svclassifier.predict(X_test)
        from sklearn.metrics import classification_report, confusion_matrix
        conf_mat.append(confusion_matrix(y_test, y_pred))
    tp,fn,fp,tn=0,0,0,0
    for i in range(10):
        tn=tn+conf_mat[i][0][0]
        fp=fp+conf_mat[i][0][1]
        fn=fn+conf_mat[i][1][0]
        tp=tp+conf_mat[i][1][1]
    avg_tn=tn//10
    avg_fp=fp//10
    avg_fn=fn//10
    avg_tp=tp//10
    acc=(avg_tn+avg_tp)/(avg_tp+avg_tn+avg_fp+avg_fn)
    MAT=[[avg_tp,avg_fn],[avg_fp,avg_tn]]
    return MAT,acc

In [17]:
import numpy as np
def svm_radial(a):
    conf_mat=[]
    for i in range(10):
        from sklearn.model_selection import train_test_split
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size =0.40)
        from sklearn.svm import SVC
        svclassifier = SVC(kernel='rbf',gamma=a)
        svclassifier.fit(X_train, y_train)
        y_pred = svclassifier.predict(X_test)
        from sklearn.metrics import classification_report, confusion_matrix
        conf_mat.append(confusion_matrix(y_test, y_pred))
    tp,fn,fp,tn=0,0,0,0
    for i in range(10):
        tn=tn+conf_mat[i][0][0]
        fp=fp+conf_mat[i][0][1]
        fn=fn+conf_mat[i][1][0]
        tp=tp+conf_mat[i][1][1]
    avg_tn=tn//10
    avg_fp=fp//10
    avg_fn=fn//10
    avg_tp=tp//10
    acc=(avg_tn+avg_tp)/(avg_tp+avg_tn+avg_fp+avg_fn)
    MAT=[[avg_tp,avg_fn],[avg_fp,avg_tn]]
    return MAT,acc

# Accuracy Purity matrix for polynomial kernel with degrees=2,3,4 and 60-40 split

In [18]:
svm_poly(2)

([[32, 53], [0, 141]], 0.7654867256637168)

In [19]:
svm_poly(3)

([[0, 86], [0, 141]], 0.6211453744493393)

In [20]:
svm_poly(4)

([[0, 85], [0, 142]], 0.6255506607929515)

# Accuracy Purity matrix for radial kernel with s=0.5,1,2 &3 and 60-40 split

In [21]:
svm_radial(0.5)

([[80, 6], [1, 140]], 0.9691629955947136)

In [22]:
svm_radial(1)

([[80, 4], [1, 141]], 0.9778761061946902)

In [23]:
svm_radial(2)

([[82, 4], [2, 138]], 0.9734513274336283)

In [24]:
svm_radial(3)

([[81, 3], [3, 139]], 0.9734513274336283)

# From the above results, it can be inferred that the radial function fits the dataset better than the polynomial function for all degrees and the radial function with s=1 gives the highest accuracy

# Leave-One out validation

In [25]:
import numpy as np
def svm_radial_loo(a):
    conf_mat=[]
    from sklearn.model_selection import train_test_split
    from sklearn.model_selection import LeaveOneOut
    from sklearn.model_selection import cross_val_predict
    from sklearn.model_selection import cross_val_score
    from sklearn.metrics import classification_report, confusion_matrix
    from sklearn.svm import SVC
    svclassifier = SVC(kernel='rbf',gamma=a)
    loo=LeaveOneOut()
    y_pred = cross_val_predict(svclassifier, X, y, cv=loo)
    conf_mat = confusion_matrix(y, y_pred)
    from sklearn.metrics import accuracy_score
    score = accuracy_score(y, y_pred)
    return conf_mat,score

In [27]:
import numpy as np
def svm_poly_loo(a):
    conf_mat=[]
    from sklearn.model_selection import train_test_split
    from sklearn.model_selection import LeaveOneOut
    from sklearn.model_selection import cross_val_predict
    from sklearn.model_selection import cross_val_score
    from sklearn.metrics import classification_report, confusion_matrix
    from sklearn.svm import SVC
    svclassifier = SVC(kernel='poly',degree=a)
    loo=LeaveOneOut()
    y_pred = cross_val_predict(svclassifier, X, y, cv=loo)
    conf_mat = confusion_matrix(y, y_pred)
    from sklearn.metrics import accuracy_score
    score = accuracy_score(y, y_pred)
    return conf_mat,score

# Accuracy Purity matrix for polynomial kernel with s=0.5,1,2 &3 and LOO Validation

In [28]:
svm_poly_loo(2)

(array([[357,   0],
        [ 91, 121]], dtype=int64), 0.8400702987697716)

In [29]:
svm_poly_loo(3)

(array([[357,   0],
        [202,  10]], dtype=int64), 0.6449912126537786)

In [30]:
svm_poly_loo(4)

(array([[357,   0],
        [212,   0]], dtype=int64), 0.6274165202108963)

# Accuracy Purity matrix for radial kernel with s=0.5,1,2 &3 and LOO Validation

In [31]:
svm_radial_loo(0.5)

(array([[355,   2],
        [  9, 203]], dtype=int64), 0.9806678383128296)

In [32]:
svm_radial_loo(1)

(array([[354,   3],
        [  9, 203]], dtype=int64), 0.9789103690685413)

In [33]:
svm_radial_loo(2)

(array([[350,   7],
        [  9, 203]], dtype=int64), 0.9718804920913884)

In [34]:
svm_radial_loo(3)

(array([[350,   7],
        [  9, 203]], dtype=int64), 0.9718804920913884)